export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";
export const GET_USER = "GET_USER";
export const DELETE_FLASH_MESSAGE = "DELETE_FLASH_MESSAGE";
export const SET_TYPES_TO_REDUX = "SET_TYPES_TO_REDUX";